apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: gianlucamori/multi-client
      context: client
      docker:
        dockerfile: DockerFile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.jsx"
          - "**/*.css"
          - "**/*.html"
    - image: gianlucamori/multi-api
      context: api
      docker:
        dockerfile: DockerFile.dev
      sync:
        infer:
          - "**/*.js"
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
      - k8s/api-deployment.yaml
      - k8s/api-cluster-ip-service.yaml
      - k8s/ingress-service.yaml
